const BookActionTypes = {
  GET_SEARCH_BOOKS: "GET_SEARCH_BOOKS",
  SET_SEACH_BOOKS_RESULT: "SET_SEACH_BOOKS_RESULT",
  GET_SAVED_BOOKS: "GET_SAVED_BOOKS",
  SET_SAVED_BOOKS_RESULT: "SET_SAVED_BOOKS_RESULT",
  ADD_BOOK_TO_SAVE: "ADD_BOOK_TO_SAVE",
  DELETE_SAVED_BOOK: "DELETE_SAVED_BOOK",
};

export default BookActionTypes;
